---
- name: SHow bgp summary in JSON
  hosts: sample
  gather_facts: yes

  tasks:
    - name: SSH and gather facts
      junipernetworks.junos.junos_facts:
      register: junos_info

    - name: Print collected data
      debug:
        var: junos_info

    - name: Print name and version
      debug:
        msg: "Device {{ junos_info.ansible_facts.ansible_net_hostname }} has version {{ junos_info.ansible_facts.ansible_net_version }}"

    - name: Show bgp summary
      junipernetworks.junos.junos_command:
        commands:
          - show bgp summary
      register: show_bgp_summary

    - name: Print STDOUT-LINES
      debug:
        var: show_bgp_summary.stdout_lines[0]

    - name: Display in JSON
      junipernetworks.junos.junos_command:
        commands:
          - "show bgp summary | display json"
      register: bgp_json

    - name: Print JSON
      debug:
        var: bgp_json
