---
- name: provision VLANS and IRB on host
  hosts: EX_ROCKET, EX_SIMBA
  gather_facts: no


  tasks:
    - name: Push config to DUT
      junipernetworks.junos.junos_config:
        lines: "{{ lookup('template', 'loop.j2') }}"
        comment: "CLI less provisioning for {{ inventory_hostname }}"
